# Starship configuration for full-stack Rust development
format = """
[░▒▓](#a3aed2)\
$os\
$username\
[▓▒░](#a3aed2)\
$directory\
$git_branch\
$git_status\
$rust\
$package\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#a3aed2 fg:#090c0c"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = "󰣀"
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = "󱘊"
Linux = "󰌽"
Fedora = "󰣛"
Arch = "󰣇"
Alpine = "󰰉"
Amazon = "󰉄"
Android = "󰀲"
CentOS = "󱄚"
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:#a3aed2 fg:#090c0c"
style_root = "bg:#a3aed2 fg:#090c0c"
format = '[$user]($style) '

[directory]
style = "bg:#769ff0 fg:#090c0c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#394260 fg:#e3e5e5"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#394260 fg:#e3e5e5"
format = '[$all_status$ahead_behind ]($style)'

[rust]
symbol = ""
style = "bg:#000000 fg:#ffffff"
format = '[ $symbol ($version) ]($style)'

[package]
symbol = "󰏗"
style = "bg:#eba0ac fg:#090c0c"
format = '[ $symbol $version ]($style)'

[cmd_duration]
min_time = 500
style = "bg:#f2cdcd fg:#090c0c"
format = '[ took $duration ]($style)'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
